version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jackexperts
      MYSQL_USER: jackexperts
      MYSQL_PASSWORD: rootjackexperts
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  nest-app:
    build:
      context: .
    container_name: nest-app
    environment:
      DATABASE_URL: 'mysql://jackexperts:rootjackexperts@mysql:3306/jackexperts'
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
volumes:
  mysql-data:
